begin;

-- Auto-generated by tools/import-teamo-csv.mjs
-- Source: teamo-members-export.csv  (1082 rows)
-- Regenerate: node tools/import-teamo-csv.mjs tools/teamo-members-export.csv supabase/seed-phase15-teamo-members.sql



-- --------------------------------------------------------------
-- TEAMS
-- --------------------------------------------------------------
insert into public.teams (id, slug, name, age_group)
values ('9f3d869d-fbf4-51a6-8b23-24a30be88214', 'under-15-boys-warwick-football-academy', 'UNDER 15 BOYS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('cf9d0278-fd7c-5177-bf23-dc06b94a9c08', 'wfa-u15-girls', 'WFA U15 Girls', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('43513f55-d4e0-56d8-9f6a-f3b5935beadd', 'u11-girls-wfa-manchester', 'U11 GIRLS - WFA MANCHESTER', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('b6cdce3b-d0b8-5300-ac78-a87171506878', 'under-13-girls-warwick-football-academy', 'UNDER 13 GIRLS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('5c9202f4-a20a-5379-85d3-73fce1d68664', 'u9-girls-wfa-inter-milan', 'U9 GIRLS - WFA INTER MILAN', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('47ea47cf-73a8-5496-9cfa-52055d2ec0be', 'wfa-pee-wee-football', 'WFA PEE WEE FOOTBALL', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('dfaa089b-cc95-56aa-a63f-47afd05e4772', 'u9-boys-wfa-juventus', 'U9 BOYS - WFA JUVENTUS', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('ceb5095d-934e-528f-9586-8438fb95180d', '2025-26-players', '2025.26 Players', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('b4dd8004-bf90-5284-8d50-4e9857519b35', 'u7-boys-skill-development', 'U7 BOYS - Skill Development', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('bdb6fe27-1760-54c2-8521-da0632661582', 'u7-boys-wfa-real-madrid', 'U7 BOYS - WFA REAL MADRID', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('eda9317b-e65a-5bd8-9f0f-edf5ba06f9fc', 'u11-boys-wfa-psv-eindhoven', 'U11 BOYS - WFA PSV EINDHOVEN', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('d54156e1-d5f0-52db-a6c2-128299971aca', 'under-13-boys-warwick-football-academy', 'UNDER 13 BOYS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('dab4ed08-ca1d-5263-8b5b-71703e7aef80', 'wfa-u13-boca-jrns', 'WFA U13 Boca Jrns.', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('d63a09a8-9cbf-579b-90f0-f61d632dfe90', 'u7-girls-valencia', 'U7 GIRLS -Valencia', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('0e1eb490-95f4-5a09-91fe-1bb2fe941ea1', 'u9-girls-wfa-napoli', 'U9 GIRLS - WFA NAPOLI', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('f4f26aa4-f98e-5529-a0e8-28c21e590ce6', 'u13-girls-wfa-independiente', 'U13 Girls - WFA Independiente', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('d429f04b-ccfe-5075-95b2-8025c5579420', 'u11-girls-wfa-liverpool', 'U11 Girls WFA Liverpool', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('b475d58e-b9ac-515a-934f-4947683cec94', 'u11-boys-paget-fc-titans', 'U11 BOYS - PAGET FC TITANS', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('78bb41ca-cf27-53dc-808d-f39794248027', 'u13-girls-wfa-racing', 'U13 Girls - WFA Racing', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('b7dccf23-4263-5536-ac73-7e8cd84de16d', 'u11-boys-wfa-ajax', 'U11 BOYS - WFA AJAX', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('6a206973-9b48-5779-830a-7e9c58c1c367', 'u18-boys-wfa', 'U18 Boys - WFA', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('bf5d6e6c-b94c-5043-ba23-9e9dcd31ea47', 'u7-boys-wfa-barcelona', 'U7 BOYS - WFA BARCELONA', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('e0c84b1b-5a86-59bb-8c80-aec5a9a069c4', 'u9-boys-wfa-roma', 'U9 BOYS - WFA ROMA', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('b74bb5e2-90f0-55d7-84b4-77bbdc05e0e8', 'u7-girls-wfa-atletico', 'U7 GIRLS - WFA ATLETICO', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('592537b2-aa53-5623-b5ed-1863ebc853e2', 'under-11-boys-warwick-football-academy', 'UNDER 11 BOYS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('a265ab6e-aa9c-5bc5-a189-ae823209d9d3', 'under-7-boys-warwick-football-academy', 'UNDER 7 BOYS - WARWICK FOOTBALL ACADEMY', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('fa778b9e-136f-599d-b72a-98394a06fe96', 'under-15-girls-wfa', 'UNDER 15 Girls - WFA', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('d869fc17-388d-58db-a7e2-c4abbb5a9b37', 'u9-girls-wfa-lazio', 'U9 GIRLS - WFA LAZIO', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('2599ff26-c327-5a9a-8363-e645555d32c5', 'under-9-boys-warwick-football-academy', 'UNDER 9 BOYS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('93b36d13-689b-5d09-a662-3a2323785090', 'under-11-girls-warwick-football-academy', 'UNDER 11 GIRLS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('13996698-0676-530d-b767-bf32d51648cb', 'under-18-boys-warwick-football-academy', 'UNDER 18 BOYS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('c811e6c2-76b0-57a9-821c-3de9f5706f4a', 'wfa-u7-boys-skills-development', 'WFA U7 Boys Skills Development', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('4d8cf9af-1962-5d46-8fcc-d5ad74b08181', 'u9-boys-paget-fc-titans', 'U9 BOYS - PAGET FC TITANS', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('85848519-a741-5999-8633-31d5fe0bfd54', 'under-7-girls-warwick-football-academy', 'UNDER 7 GIRLS - WARWICK FOOTBALL ACADEMY', 'Mini')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('ba762b40-3757-516d-a112-e479d13a38b4', 'wfa-u13-river-plate', 'WFA U13 River Plate', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;
insert into public.teams (id, slug, name, age_group)
values ('0a68fc72-f605-54ea-a91e-29c42e272f94', 'under-9-girls-warwick-football-academy', 'UNDER 9 GIRLS - WARWICK FOOTBALL ACADEMY', 'Youth')
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, age_group = excluded.age_group;


commit;
