begin;

insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'ba43f4a9-c863-5f38-8f20-02e08658a1bf',
  '43513f55-d4e0-56d8-9f6a-f3b5935beadd',
  'Teddy Terceira',
  null,
  null,
  '1983-02-22',
  'male',
  null,
  'teddy@terceiras.bm',
  '14417047374',
  '2023-10-27',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'FL05',
  'Guardian, father: Emile Terceira, Guardian, Father: Lee Terceira',
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '656355ae-4986-5060-866d-a56d4b736262',
  '9f3d869d-fbf4-51a6-8b23-24a30be88214',
  'Sophie Tindall',
  null,
  null,
  '2011-11-19',
  'female',
  null,
  null,
  null,
  '2023-10-29',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '6283144f-d17d-5444-a82a-e9c4f71f89b3',
  'bdb6fe27-1760-54c2-8521-da0632661582',
  'Elijah Todd',
  null,
  null,
  '2018-07-16',
  'male',
  null,
  null,
  null,
  '2023-11-04',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  'Bermuda',
  null,
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '913c284c-7b61-5111-8e00-da193678c4f1',
  '43513f55-d4e0-56d8-9f6a-f3b5935beadd',
  'Inara Todd',
  null,
  null,
  '2016-01-03',
  'female',
  null,
  null,
  null,
  '2024-06-11',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'DD02',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '3569a89c-c748-52e5-8c9e-16d678b2225b',
  'ceb5095d-934e-528f-9586-8438fb95180d',
  'Richard Todd',
  null,
  null,
  '1972-01-05',
  'male',
  null,
  'football@warwick.bm',
  '14413371120',
  '2023-09-21',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'DD02',
  'Guardian, father: test child, Guardian, Father: Inara Todd',
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '633482fb-1801-5b0a-83cd-254139a8eaa8',
  'd429f04b-ccfe-5075-95b2-8025c5579420',
  'Tiffanie Todd',
  null,
  null,
  '1980-06-24',
  'female',
  null,
  'toddbda@gmail.com',
  '14417041120',
  '2023-10-06',
  null,
  false,
  true,
  true,
  true,
  '3 Cove Valley Lane',
  'St, Davids',
  null,
  'DD02',
  'Guardian, Mother: Inara Todd',
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'ab442ff2-814b-50fd-9c79-694fe7221c53',
  'ceb5095d-934e-528f-9586-8438fb95180d',
  'Theodore Tolaram',
  null,
  null,
  '2013-01-18',
  'male',
  null,
  null,
  null,
  '2023-11-01',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '68c82400-d066-5c2c-9de5-65c04a6cc7db',
  'b475d58e-b9ac-515a-934f-4947683cec94',
  'Magnus Tolhurst',
  null,
  null,
  '2015-08-23',
  'male',
  null,
  null,
  null,
  '2023-10-30',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'FL04',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '4f96f59c-587e-5426-a547-84191b800f30',
  'b4dd8004-bf90-5284-8d50-4e9857519b35',
  'G''ary Trott-Brangman',
  null,
  null,
  '2018-03-27',
  'male',
  null,
  null,
  null,
  '2023-11-10',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'f99fd381-408c-5f98-bab3-ba0fce2513ac',
  'd54156e1-d5f0-52db-a6c2-128299971aca',
  'Ajani Trott',
  null,
  null,
  '2013-03-11',
  'male',
  null,
  null,
  null,
  '2026-04-13',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'Wk09',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'b3877c51-eb63-53a7-8bfc-845178c02f7b',
  '6a206973-9b48-5779-830a-7e9c58c1c367',
  'Cairo Tucker',
  null,
  null,
  '2008-04-24',
  'male',
  null,
  'tuckercairo1985@gmail.com',
  '14417074494',
  '2023-10-20',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'CR04',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '9e987734-33b3-5c53-826b-38d2eb500e53',
  'eda9317b-e65a-5bd8-9f0f-edf5ba06f9fc',
  'Dylan Tuckett',
  null,
  29,
  '2014-07-09',
  'male',
  null,
  null,
  null,
  '2023-10-26',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'HM01',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '42b9600e-67e1-59d2-a210-58562e646bf2',
  'eda9317b-e65a-5bd8-9f0f-edf5ba06f9fc',
  'Reggie Jr Tuckett',
  null,
  null,
  null,
  'male',
  null,
  'rtuckjr@logic.bm',
  '14417073643',
  '2023-10-26',
  null,
  false,
  true,
  true,
  true,
  '13 Seagull LaneLower Apt',
  null,
  null,
  'HM01',
  'Guardian, Father: Dylan Tuckett',
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '367c3964-57a5-5a60-b09c-f72f3f7d40ce',
  '2599ff26-c327-5a9a-8363-e645555d32c5',
  'Elijah Ugono',
  null,
  null,
  '2018-04-13',
  'male',
  null,
  null,
  null,
  '2026-06-29',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'WK 02',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '1aac7d92-3d67-5dcb-bf19-9c094181189d',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Freya Ugono',
  null,
  null,
  '2021-03-17',
  'female',
  null,
  null,
  null,
  '2026-01-09',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'WK 02',
  null,
  'Out',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '253060aa-bfaa-52f7-8c32-74257f5eb636',
  'c811e6c2-76b0-57a9-821c-3de9f5706f4a',
  'Charles Urbina',
  null,
  null,
  '2020-07-13',
  'male',
  null,
  null,
  null,
  '2024-06-29',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'HM06',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '253060aa-bfaa-52f7-8c32-74257f5eb636',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Charles Urbina',
  null,
  null,
  '2020-07-13',
  'male',
  null,
  null,
  null,
  '2024-11-23',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'hm06',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '4cd7770a-1198-5afc-b284-bcc0bc3aeb88',
  'ceb5095d-934e-528f-9586-8438fb95180d',
  'Thomas Valadao',
  null,
  null,
  '2014-03-12',
  'male',
  null,
  null,
  null,
  '2023-10-30',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'WK08',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '479bbb1d-bbef-5f9d-aad3-4d793d2cee02',
  '93b36d13-689b-5d09-a662-3a2323785090',
  'Freida Valli',
  null,
  null,
  '2013-02-15',
  'female',
  null,
  null,
  null,
  '2024-03-15',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'FL05',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'fe28c903-5bd2-52c0-b9c6-1eb272e0740c',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Vanessa Vargas',
  null,
  null,
  '2019-11-29',
  'female',
  null,
  null,
  null,
  '2024-06-24',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'WK07',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'd2f110bf-444c-5fc7-81d2-bcaa9b5c05ea',
  '85848519-a741-5999-8633-31d5fe0bfd54',
  'Elisa von Reitzenstein',
  null,
  null,
  '2020-01-29',
  'female',
  null,
  null,
  null,
  '2026-06-20',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'PG06',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'eaed77ed-df7d-5a3d-83b3-d8d6784de80a',
  'd869fc17-388d-58db-a7e2-c4abbb5a9b37',
  'Leonie von Reitzenstein',
  null,
  null,
  '2017-03-25',
  'female',
  null,
  null,
  null,
  '2025-01-08',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'PG06',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'b61e9c48-31ae-5d43-bb2e-7472c0ee4f62',
  'd869fc17-388d-58db-a7e2-c4abbb5a9b37',
  'Nicole von Reitzenstein',
  null,
  null,
  null,
  'female',
  null,
  'suhnern@gmail.com',
  '14417042909',
  '2025-01-08',
  null,
  false,
  true,
  true,
  true,
  '20 Tankfield hill',
  'Paget',
  'Bermuda',
  'PG06',
  'Guardian, mother: Leonie von Reitzenstein, Guardian, mother: Elisa von Reitzenstein',
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'b7702901-225a-5856-a7fd-70e45e0ec47e',
  'ceb5095d-934e-528f-9586-8438fb95180d',
  'Casey Walden',
  null,
  null,
  '2011-03-11',
  'female',
  null,
  null,
  null,
  '2023-11-02',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'f58e0b7f-14cb-5299-b176-4a8d7e8e9a63',
  'd54156e1-d5f0-52db-a6c2-128299971aca',
  'Cullen Walden',
  null,
  null,
  '2013-05-17',
  'male',
  null,
  null,
  null,
  '2023-11-03',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'e4d131a7-5e1d-57f4-994c-0ae76a16ee52',
  'b7dccf23-4263-5536-ac73-7e8cd84de16d',
  'Jaden Walrond',
  null,
  2,
  '2014-08-11',
  'male',
  null,
  null,
  null,
  '2023-10-18',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'PG04',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'f6072636-cc07-5412-a351-2b83155f79c8',
  'b7dccf23-4263-5536-ac73-7e8cd84de16d',
  'Karen Walrond',
  null,
  null,
  null,
  'female',
  null,
  'karlynton@hotmail.com',
  '14415998157',
  '2023-10-18',
  null,
  false,
  true,
  true,
  true,
  '21 Cataract Hill',
  null,
  null,
  'PG04',
  'Guardian, Mother: Jaden Walrond',
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '6156d37a-33c3-5c2c-b789-669db02ce88a',
  'ceb5095d-934e-528f-9586-8438fb95180d',
  'James Watson',
  null,
  null,
  '2019-04-17',
  'male',
  null,
  null,
  null,
  '2023-11-17',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'HM06',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'a8998af1-4ae6-5b6c-8385-217ac94c54b9',
  'd429f04b-ccfe-5075-95b2-8025c5579420',
  'Rayven Weeks',
  null,
  null,
  '2015-12-01',
  'female',
  null,
  null,
  null,
  '2025-12-01',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'FL02',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '2a1cfaa2-32f9-544d-800d-b42864d13698',
  'dfaa089b-cc95-56aa-a63f-47afd05e4772',
  'Christopher Wheatley',
  'Winger/Striker',
  18,
  '2017-05-18',
  'male',
  null,
  null,
  null,
  '2024-06-04',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'HM06',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'bf60297b-ceeb-5c47-8a90-ffb6d6d08821',
  'dfaa089b-cc95-56aa-a63f-47afd05e4772',
  'Sean Wheatley',
  null,
  null,
  '1983-03-18',
  null,
  null,
  'seancwheatley@gmail.com',
  '14415992225',
  '2024-06-21',
  null,
  false,
  true,
  true,
  false,
  'C114 Rockville Lane',
  'Pembroke',
  null,
  'HM06',
  'Guardian, Father: Christopher Wheatley, Guardian, Step Father: Nathan Medeiros',
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '29d030e4-60aa-5190-a663-26c2f93349c4',
  'e0c84b1b-5a86-59bb-8c80-aec5a9a069c4',
  'Zakai White',
  null,
  null,
  '2016-09-22',
  'male',
  null,
  null,
  null,
  '2024-07-02',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'SN03',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '083a0878-4d15-5658-81df-707a995bc1a0',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Ennis Willens',
  null,
  null,
  '2019-01-05',
  'male',
  null,
  null,
  null,
  '2024-09-20',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'DV07',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '66ac5f10-416e-5cff-99b4-fc626479d356',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Theo Willens',
  null,
  null,
  '2020-06-19',
  'male',
  null,
  null,
  null,
  '2024-08-12',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'DV07',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '05eaaeab-cb7b-5f04-9292-ed3867409dfb',
  'e0c84b1b-5a86-59bb-8c80-aec5a9a069c4',
  'Joshua Williams',
  null,
  null,
  '2016-12-23',
  'male',
  null,
  null,
  null,
  '2024-08-28',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '05eaaeab-cb7b-5f04-9292-ed3867409dfb',
  '2599ff26-c327-5a9a-8363-e645555d32c5',
  'Joshua Williams',
  null,
  null,
  '2016-12-23',
  'male',
  null,
  null,
  null,
  '2025-06-19',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'SN01',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'dcd2d84e-8d9d-598b-a4ab-6734e42c281b',
  'b4dd8004-bf90-5284-8d50-4e9857519b35',
  'Rhys Williams',
  null,
  null,
  '2020-07-05',
  'male',
  null,
  null,
  null,
  '2024-06-04',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'DV03',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '7df7e59e-7a3a-5a20-aebd-b376cf0774fc',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Blake Wilsen',
  null,
  null,
  '2020-06-11',
  'male',
  null,
  null,
  null,
  '2024-09-04',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'FL06',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '3fb1b3ec-4097-5b77-a449-b88f15d1d11d',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Cody Wilsen',
  null,
  null,
  '2020-06-11',
  'male',
  null,
  null,
  null,
  '2024-09-04',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'FL06',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'd2ed1ffb-3a19-5c4a-b9b1-3bd794a9f253',
  'cf9d0278-fd7c-5177-bf23-dc06b94a9c08',
  'Ryley Wilson',
  null,
  null,
  '2009-10-26',
  'female',
  null,
  null,
  null,
  '2024-05-29',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'DV07',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'b4fe9a5b-8f84-500e-8811-79a9113b381e',
  '78bb41ca-cf27-53dc-808d-f39794248027',
  'Victory Wilson',
  null,
  null,
  '2013-08-03',
  'female',
  null,
  null,
  null,
  '2025-10-31',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'MA01',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '00ceab57-a71c-5798-89d0-01223878ec61',
  '85848519-a741-5999-8633-31d5fe0bfd54',
  'Audrey Wong',
  null,
  null,
  '2019-08-15',
  'male',
  null,
  null,
  null,
  '2024-06-12',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '638228a4-ad9f-53b5-84de-edacec116df4',
  'c811e6c2-76b0-57a9-821c-3de9f5706f4a',
  'Ethan Wong',
  null,
  null,
  '2019-08-15',
  'male',
  null,
  null,
  null,
  '2024-01-19',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '83b27f4d-62fd-5668-bbd5-d4a64923f4ea',
  'e0c84b1b-5a86-59bb-8c80-aec5a9a069c4',
  'ELLIOT WOOD',
  null,
  null,
  '2017-12-18',
  'male',
  null,
  null,
  null,
  '2023-11-28',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  'WK 01',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'aa22478f-7ff5-5597-bb7b-abc14116ff16',
  '2599ff26-c327-5a9a-8363-e645555d32c5',
  'Hughes Woodward',
  null,
  null,
  '2016-07-16',
  'male',
  null,
  null,
  null,
  '2025-06-23',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'HM05',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '4a57fafd-212d-5fc2-80aa-117906e034ab',
  '47ea47cf-73a8-5496-9cfa-52055d2ec0be',
  'Parker Woodward',
  null,
  null,
  '2019-08-31',
  'male',
  null,
  null,
  null,
  '2024-05-29',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  'Bermuda',
  'HM05',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '5accd2e9-de4f-53d4-ae98-a5fc5df69c27',
  'b7dccf23-4263-5536-ac73-7e8cd84de16d',
  'Isaac Wookey',
  null,
  null,
  '2014-07-05',
  'male',
  null,
  null,
  null,
  '2024-05-31',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'FL 05',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '9811f143-7eed-59d7-a699-4f05fbf06197',
  'bf5d6e6c-b94c-5043-ba23-9e9dcd31ea47',
  'Nicola Yanev',
  null,
  null,
  '2017-12-18',
  'male',
  null,
  null,
  null,
  '2023-11-03',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'PG01',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'f2399ab9-f74c-5a10-9d06-762ab9abd3dc',
  'bf5d6e6c-b94c-5043-ba23-9e9dcd31ea47',
  'Peter Yanev',
  null,
  null,
  '2017-12-18',
  'male',
  null,
  null,
  null,
  '2023-11-03',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'PG01',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'ffc55e88-628d-5b9e-b218-f70a9292fe03',
  'b4dd8004-bf90-5284-8d50-4e9857519b35',
  'Leo Yiasoumi',
  null,
  null,
  '2019-03-30',
  'male',
  null,
  null,
  null,
  '2023-11-05',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'sb02',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'ecb7866a-5879-5873-8e92-d11f407b6779',
  'd429f04b-ccfe-5075-95b2-8025c5579420',
  'Evangeline York',
  'mid field',
  8,
  '2015-11-07',
  'female',
  null,
  null,
  null,
  '2023-10-27',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  null,
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '73516539-22cd-5303-b1ba-00f0d76de573',
  'ceb5095d-934e-528f-9586-8438fb95180d',
  'Genevieve York',
  null,
  null,
  '2013-09-30',
  'male',
  null,
  null,
  null,
  '2023-10-30',
  null,
  false,
  true,
  true,
  false,
  null,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'be87d31a-d092-5bb4-b7ac-9aa3e502e05a',
  'e0c84b1b-5a86-59bb-8c80-aec5a9a069c4',
  'Aaron Young',
  null,
  null,
  '2016-06-29',
  'male',
  null,
  null,
  null,
  '2023-11-03',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'PG01',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  '452ede10-4072-5b66-a193-9935b6595347',
  'bdb6fe27-1760-54c2-8521-da0632661582',
  'Hudson Young',
  null,
  null,
  '2018-03-26',
  'male',
  null,
  null,
  null,
  '2024-06-12',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'CR01',
  null,
  'In',
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;
insert into public.players (
  id, team_id, full_name, position, shirt_number,
  date_of_birth, gender, member_number, email, phone,
  joined_at, occupation, first_aider, photo_permission, publication_consent,
  has_medical_data, address_line1, address_city, address_country, address_postcode,
  family_code, season_opt_in, ngb_registration, notes, last_active, active
)
values (
  'dcaa1009-bf0f-50aa-b789-6ebed668f6f0',
  'b475d58e-b9ac-515a-934f-4947683cec94',
  'Rostyslav Zakharov',
  null,
  null,
  '2014-05-29',
  'male',
  null,
  null,
  null,
  '2023-11-15',
  null,
  false,
  true,
  true,
  true,
  null,
  null,
  null,
  'CR02',
  null,
  null,
  false,
  null,
  null,
  true
)
on conflict (id) do update set
  team_id = excluded.team_id,
  full_name = excluded.full_name,
  position = excluded.position,
  shirt_number = excluded.shirt_number,
  date_of_birth = excluded.date_of_birth,
  gender = excluded.gender,
  member_number = excluded.member_number,
  email = excluded.email,
  phone = excluded.phone,
  joined_at = excluded.joined_at,
  occupation = excluded.occupation,
  first_aider = excluded.first_aider,
  photo_permission = excluded.photo_permission,
  publication_consent = excluded.publication_consent,
  has_medical_data = excluded.has_medical_data,
  address_line1 = excluded.address_line1,
  address_city = excluded.address_city,
  address_country = excluded.address_country,
  address_postcode = excluded.address_postcode,
  family_code = excluded.family_code,
  season_opt_in = excluded.season_opt_in,
  ngb_registration = excluded.ngb_registration,
  notes = excluded.notes,
  last_active = excluded.last_active;


commit;
